### ISSUE TITLE
"Cannot find module 'handlebars'" when running examples

### ISSUE THREAD

**Issue by bitshiftnetau** [ericf/express-handlebars#276]
Can't even run up a basic example. 

- Cloned this repo, cd into examples/basic
- 'npm install'
- nodemon server.js
- (after following output) manually installed handlebars, still same error

Output:

```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'handlebars'
Require stack:
- /home/access/code/web/node/express-handlebars/lib/express-handlebars.js
- /home/access/code/web/node/express-handlebars/index.js
- /home/access/code/web/node/express-handlebars/examples/advanced/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/access/code/web/node/express-handlebars/lib/express-handlebars.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/access/code/web/node/express-handlebars/lib/express-handlebars.js',
    '/home/access/code/web/node/express-handlebars/index.js',
    '/home/access/code/web/node/express-handlebars/examples/advanced/server.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by bitshiftnetau** [comment]
please disregard
