### ISSUE TITLE
exphbs is not a function

### ISSUE THREAD

**Issue by habfem** [ericf/express-handlebars#297]
TypeError: exphbs is not a function
    at Object.<anonymous> (C:\Users\habee\3D Objects\NODE\EXPRESS_CRASH\index.js:13:26)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

Is anyone else getting this type of error

**Comment by UziTech** [comment]
All new development of express-handlebars is done on a new repo [express-handlebars/express-handlebars](https://github.com/express-handlebars/express-handlebars). Please create an issue there and add more info like the version of express-handlebars and node and some example code that produces the error.

**Comment by habfem** [comment]
Thanks. That was really helpful

**Comment by habfem** [comment]
.engine pretty much solves my problem
